version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Singapore
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Singapore
    labels:
      - dependencies
      - docker
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Singapore
    labels:
      - dependencies
      - ci
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
